### ISSUE TITLE
no model given

### ISSUE THREAD

**Issue by westpilgrim** [zimpha/EdgeBoxes#1]
hi ,you forget to give the model model.bin. would you please add the model?

**Comment by zimpha** [comment]
Model for ACFDetector comes from [pdollar/toolbox](https://github.com/pdollar/toolbox/tree/master/detector/models) and as for EdgeDetector, it comes from [pdollar/edges](https://github.com/pdollar/edges/tree/master/models/forest).

I just turn the Matlab model to a binary file. You can refer to the load model functions in [ACFDetector.cpp](https://github.com/zimpha/EdgeBoxes/blob/master/src/ACFDetector.cpp) and [EdgeDetector.cpp](https://github.com/zimpha/EdgeBoxes/blob/master/src/EdgeDetector.cpp) for details.

**Comment by westpilgrim** [comment]
thx
