### ISSUE TITLE
how to get the model

### ISSUE THREAD

**Issue by SJTUzhanglj** [zimpha/EdgeBoxes#3]
I generate this project on Windows.
but where to get the model.bin as:

detector.loadModel("./model/model.bin");

**Comment by zimpha** [comment]
you can refer to [this](https://github.com/zimpha/EdgeBoxes/issues/1).

**Comment by SJTUzhanglj** [comment]
I tried to load the modelbsds.mat in edge_demo, but it turned out to be some wrong data. i check the mat in matlab and find the params as imwidth,ntrees ,etc in a struct 'opts'.

```
    imWidth 1280590157  int
    gtWidth 924860993   int
    nTrees  1293955886  int
    nTreeNodes  1714246721  int
    nOrients    744844393   int
    grdSmooth   2.72450326e+20  float
```

**Comment by zimpha** [comment]
You should first convert the modelbsds.mat to binary file. As for the format, you can refer [this](https://github.com/zimpha/EdgeBoxes/issues/1).

**Comment by SJTUzhanglj** [comment]
Sorry to bother.. but i cannot find the .mat to .bin converter function in the ACFDetecter and EdgeDetector classes. I'll be greatly appreciated if you can show me that in detail。

**Comment by SJTUzhanglj** [comment]
Can you share the model.bin file you converted? I have no idea how to convert the .mat file to .bin even if i know the format exactly. Only way i can know is to read the .mat using C++ with matlab-cpp engine
